[package]
name = "k210-example"
version = "0.1.1"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
edition = "2018"

[dependencies]
panic-halt = "0.2.0"
riscv = "0.6.0"
riscv-rt = "0.8.0"
k210-hal = "0.2.0"
